### ISSUE TITLE
Slowing down the speech engine

### ISSUE THREAD

**Issue by ghost** [gromnitsky/read-aloud.el#2]
Can you help me slow down the engine. I am using jampal. 

I have this in my init.el file:

(setq read-aloud-engine "jampal.en")

**Comment by gromnitsky** [comment]
You'll need to add an a custom entry to the list of engines:

~~~
(lax-plist-put read-aloud-engines "my-jampal"
  '(cmd "cscript"
                args ("C:\\Program Files\\Jampal\\ptts.vbs" "-r" "4")) )
~~~

Where the number 4 is your *speech rate*. Valid values are -10...10, hence to slow it down, set it, for example, to 0.

Then temporarily select this new engine entry via

    M-x read-aloud-change-engine

or permanently by

    (setq read-aloud-engine "my-jampal")

in your init file.
